WWWDIR = /home/rgonsuron/src/system/home/www-data
dist:
	sudo cp -up index.* $(WWWDIR)
	sudo cp -rup rdsadmin $(WWWDIR)
	sudo cp -rup rdsmwd $(WWWDIR)
	sudo cp -rup rdsdd $(WWWDIR)
	sudo cp -rup rdsop $(WWWDIR)
	sudo cp -rup rdsdf $(WWWDIR)
	sudo cp -rup rdsdfrw $(WWWDIR)
	sudo cp -rup rdsroot $(WWWDIR)

clean:
	sudo rm -rf $(WWWDIR)/index.* $(WWWDIR)/rds* /tmp/rdsadmin/* /tmp/rdsmwd/* /tmp/rdsop/* /tmp/rdsdd/* /tmp/rdsdf/*

