<?php /*
	Written by: Richard Gonsuron
	Copyright: 2009, Digital Oil Tools
	All rights reserved.
	NOTICE: This file is solely owned by Digital Oil Tools You may NOT modify, copy,
	or distribute this file in any manner without written permission of Digital Oil Tools
*/ ?>
<?php
// $seldbname=$_GET['seldbname'];
if(strlen($seldbname)<=0)	$seldbname=$_GET['seldbname'];
if(strlen($filename)<=0)	$filename=$_GET['filename'];
$cutoff=$_GET['cutoff'];
if(strlen($mintvd)<=0)	$mintvd=$_GET['mintvd'];
if(strlen($maxtvd)<=0)	$maxtvd=$_GET['maxtvd'];
if(strlen($minvs)<=0)	$minvs=$_GET['minvs'];
if(strlen($maxvs)<=0)	$maxvs=$_GET['maxvs'];
if(strlen($yscale)<=0)	$yscale=$_GET['yscale'];
$yscale/=100;
if(strlen($cutoff)<=0)	$cutoff=200;

require('/usr/share/php/fpdf/fpdf.php');
require_once("dbio.class.php");
$db=new dbio($seldbname);
$db->OpenDb();
include('readwellinfo.inc.php');
$db->CloseDb();
$tofile=0;
if(strlen($filename)>0) $tofile=1;
else $filename=sprintf("tmp/%s.surveyvs.pdf", $seldbname);
if(file_exists($filename)) unlink($filename);

$imagefn="tmp/$seldbname.surveyplotvs.png";
if(file_exists($imagefn)) unlink($imagefn);

$args=" -t vs";
if(strlen($cutoff))	$args=$args." -c $cutoff";
$args=$args." -p $projection";
$args=$args." -o $imagefn";
$args=$args." -h 1148";
$args=$args." -w 792";
if(strlen($mintvd))	$args=$args." -tvd1 $mintvd";
if(strlen($maxtvd))	$args=$args." -tvd2 $maxtvd";
if(strlen($minvs))	$args=$args." -vs1 $minvs";
if(strlen($maxvs))	$args=$args." -vs2 $maxvs";
if(strlen($yscale))	$args=$args." -yscale $yscale";
exec("./sses_ps -d $seldbname $args");

class PDF extends FPDF
{
	var $db;

	function ReportHeader()
	{
		$h=.15;
		$w1=1.0;
		$w2=1.75;
		$w3=0.64;

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows() > 0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
		}

		// $this->SetFillColor(255,255,255);
		$this->SetFillColor(230, 230, 190);

		$this->SetMargins(2.5,0,.25);
		$this->SetY(0.5);
		$this->SetX(4.0);
		$this->SetFontSize('5');
		$this->Cell(4.0, .1, "Generated by: Subsurface Geological Tracking Analysis", "TR", 2, 'R', true);
		$this->Cell(4.0, .1, "Copyright 2010-2011 Digital Oil Tools", "R", 1, 'R', true);
		$this->Cell(5.5, .5, "", "R", 0, 'C', true);

		$this->SetFont('','B',14);
		$this->SetY(0.5);
		$this->Cell(.7, .55, "", "TL", 0, 'C', true);
		$this->Cell(2.8, .5, "Vertical Section Plot", "T", 1, 'C', true);

		$this->SetFont('','',7);
		$this->Image("./logofull.png", 2.52, .52, .6, .5);

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
			$companyname=$this->db->FetchField("operatorname");
			$jobnumber=$this->db->FetchField("jobnumber");
			$operatorcontact=$this->db->FetchField("operatorcontact1");
			$rigid=$this->db->FetchField("rigid");
			$startdate=$this->db->FetchField("startdate");
			$apiuwi=$this->db->FetchField("wellid");
			$enddate=$this->db->FetchField("enddate");
			$field=$this->db->FetchField("field");
			$location=$this->db->FetchField("location");
			$propazm=$this->db->FetchField("propazm");
			$stateprov=$this->db->FetchField("stateprov");
			$northref=$this->db->FetchField("correction");
			$county=$this->db->FetchField("county");
		}

		$this->Cell($w1, $h, "Company Name:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $companyname, 0, 0, 'L', true);
		$this->Cell($w1, $h, "Job Number:", 0, 0, 'R', true);
		$this->Cell($w2, $h, $jobnumber, "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "Well Name:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $wellname, 0, 0, 'L', true);
		$this->Cell($w1, $h, "", 0, 0, 'R', true);
		$this->Cell($w2, $h, "", "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "Rig ID:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $rigid, 0, 0, 'L', true);
		$this->Cell($w1, $h, "Start Date:", 0, 0, 'R', true);
		$this->Cell($w2, $h, $startdate, "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "API/UWI:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $apiuwi, 0, 0, 'L', true);
		$this->Cell($w1, $h, "End Date:", 0, 0, 'R', true);
		$this->Cell($w2, $h, $enddate, "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "Field:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $field, 0, 0, 'L', true);
		$this->Cell($w1, $h, " ", 0, 0, 'R', true);
		$this->Cell($w2, $h, " ", "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "Location:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $location, 0, 0, 'L', true);
		$this->Cell($w1, $h, "Proposed Azimuth:", 0, 0, 'R', true);
		$this->Cell($w2, $h, $propazm, "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "State/Prov:", "L", 0, 'R', true);
		$this->Cell($w2, $h, $stateprov, 0, 0, 'L', true);
		$this->Cell($w1, $h, "North Reference:", 0, 0, 'R', true);
		$this->Cell($w2, $h, $northref, "R", 0, 'L', true);
		$this->Ln();

		$this->Cell($w1, $h, "County:", "LB", 0, 'R', true);
		$this->Cell($w2, $h, $county, "B", 0, 'L', true);
		$this->Cell($w1, $h, "", "B", 0, 'C', true);
		$this->Cell($w2, $h, "", "RB", 0, 'C', true);
		$this->Ln();

		$this->Ln();
	}

	function ReportSurveys() {
		$db2=$this->db2;
		$db2->DoQuery("select * from addforms;");
		$totid =null;
		$botid = null;
		while($db2->FetchRow()){
			
			if(trim($db2->FetchField('label'))=='TOT'){
				$totid = $db2->FetchField('id');
			}
			if(trim($db2->FetchField('label'))=='BOT'){
				$botid = $db2->FetchField('id');
			}
		}
		$this->db->DoQuery("SELECT count(id) FROM surveys WHERE plan=0");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$numsvys=$this->db->FetchField("count");
		}

		$this->db->DoQuery("SELECT * FROM surveys WHERE plan=0 ORDER BY md DESC LIMIT 1");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$id= $this->db->FetchField("id");
			if($totid){
				$query = "select tot from addformsdata where svyid=$id and infoid=$totid;";
			 	$db2->DoQuery($query);
				$db2->FetchRow();
				$tot =sprintf("%.2f", $db2->FetchField("tot"));
			}
			if($botid){
				$query = "select tot from addformsdata where svyid=$id and infoid=$botid;";
				$db2->DoQuery($query);
				$db2->FetchRow();
				$bot =sprintf("%.2f", $db2->FetchField("tot"));
			}				
			$svymd=$this->db->FetchField("md");
			$svyinc=$this->db->FetchField("inc");
			$svyazm=$this->db->FetchField("azm");
			$svytvd=$this->db->FetchField("tvd");
			$svyvs=$this->db->FetchField("vs");
			$svydl=$this->db->FetchField("dl");
			$svyca=$this->db->FetchField("ca");
			$svycd=$this->db->FetchField("cd");
			$svyns=$this->db->FetchField("ns");
			$svyew=$this->db->FetchField("ew");
			$tlc = $this->db->FetchField("tot");
			$svytot=$tot;
			$svybot=$bot;
			$svydip=$this->db->FetchField("dip");
			$svyfault=$this->db->FetchField("fault");
		}

		$h=.125;
		$w1=0.50;
		$w2=0.36;
		$b=1;
		//$left=3.75;
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(110, 174, 126);
		$this->Cell($w2, $h, "Svy", $b, 0, 'C', true);
		$this->Cell($w1, $h, "Depth", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Inc", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Azm", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TVD", $b, 0, 'C', true);
		$this->Cell($w1, $h, "VS", $b, 0, 'C', true);
		$this->Cell($w2, $h, "DL", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TCL", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Pos-TCL", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TOT", $b, 0, 'C', true);
		$this->Cell($w1, $h, "BOT", $b, 0, 'C', true);
		$this->Cell($w2, $h, "DIP", $b, 0, 'C', true);
		$this->Cell($w2, $h, "FAULT", $b, 0, 'C', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(230, 230, 190);
		$this->Cell($w2, $h, sprintf("%d",$numsvys-1), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(250, 148, 148);
		$this->db->DoQuery("SELECT * FROM surveys WHERE plan>0 ORDER BY md ASC");

		if($this->db->FetchNumRows()>0) {
			$i=0;
			while ($this->db->FetchRow()) {
				$omd= $this->db->FetchField("md");
				if($totid){
					$query = "select tot from addformsdata where md=$omd and infoid=$totid;";
				 	$db2->DoQuery($query);
					$db2->FetchRow();
					$tot =sprintf("%.2f", $db2->FetchField("tot"));
				}
				if($botid){
					$query = "select tot from addformsdata where md=$omd and infoid=$botid;";
					$db2->DoQuery($query);
					$db2->FetchRow();
					$bot =sprintf("%.2f", $db2->FetchField("tot"));
				}				
				$svymd=$this->db->FetchField("md");
				$svyinc=$this->db->FetchField("inc");
				$svyazm=$this->db->FetchField("azm");
				$svytvd=$this->db->FetchField("tvd");
				$svyvs=$this->db->FetchField("vs");
				$svydl=$this->db->FetchField("dl");
				$svyca=$this->db->FetchField("ca");
				$svycd=$this->db->FetchField("cd");
				$svyns=$this->db->FetchField("ns");
				$svyew=$this->db->FetchField("ew");
				$tlc = $this->db->FetchField("tot");
				$svytot=$tot;
				$svybot=$bot;
				$svydip=$this->db->FetchField("dip");
				$svyfault=$this->db->FetchField("fault");

				
				if($i==0) $this->Cell($w2, $h, "BPrj", $b, 0, 'R', true);
				else $this->Cell($w2, $h, "PAhd", $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
				$this->Ln(); $this->hdrheight+=$h;
				$i++;
			}
		}
	}

	function ReportProjections() {
		$db2=$this->db2;
		$h=.125;
		$w1=0.50;
		$w2=0.36;
		$b=1;
		//$left=3.75;
		$this->SetFillColor(250, 148, 148);
		$db2->DoQuery("select * from addforms;");
		$totid =null;
		$botid = null;
		while($db2->FetchRow()){
			
			if(trim($db2->FetchField('label'))=='TOT'){
				$totid = $db2->FetchField('id');
			}
			if(trim($db2->FetchField('label'))=='BOT'){
				$botid = $db2->FetchField('id');
			}
		}
		$this->db->DoQuery("SELECT * FROM projections ORDER BY md ASC");
		if($this->db->FetchNumRows()>0) {
			$i=1;
			while ($this->db->FetchRow()) {
				$id = $this->db->FetchField("id");
				if($totid){
							$query = "select tot from addformsdata where projid=$id and infoid=$totid;";
							$db2->DoQuery($query);
							$db2->FetchRow();
							$tot =sprintf("%.2f", $db2->FetchField("tot"));
						}
				if($botid){
					$query = "select tot from addformsdata where projid=$id and infoid=$botid;";
					$db2->DoQuery($query);
					$db2->FetchRow();
					$bot =sprintf("%.2f", $db2->FetchField("tot"));
				}
				$svymd=$this->db->FetchField("md");
				$svyinc=$this->db->FetchField("inc");
				$svyazm=$this->db->FetchField("azm");
				$svytvd=$this->db->FetchField("tvd");
				$svyvs=$this->db->FetchField("vs");
				$svydl=$this->db->FetchField("dl");
				$svyca=$this->db->FetchField("ca");
				$svycd=$this->db->FetchField("cd");
				$svyns=$this->db->FetchField("ns");
				$svyew=$this->db->FetchField("ew");
				$tlc = $this->db->FetchField("tot");
				$svytot=$tot;
				$svybot=$bot;
				$svydip=$this->db->FetchField("dip");
				$svyfault=$this->db->FetchField("fault");

				
				$this->Cell($w2, $h, "PA$i", $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
				$this->Ln(); $this->hdrheight+=$h;
				$i++;
			}
		}
		$this->Ln(); $this->hdrheight+=$h;
	}

	function PlotImage($fn)
	{
		$this->Image($fn, 0.25, 0.25, 8.0, 10.5);
	}
}

$pdf=new PDF("P", "in", "Letter");
$pdf->SetFont('Arial','',8);
$pdf->AddPage();
$pdf->db=new dbio($seldbname);
$pdf->db->OpenDb();
$pdf->db2=new dbio($seldbname);
$pdf->db2->OpenDb();
$pdf->PlotImage($imagefn);
$pdf->ReportHeader();
$pdf->SetMargins(2.75,0,.25);
$pdf->ReportSurveys();
$pdf->ReportProjections();
$pdf->db->CloseDb();
$pdf->db2->CloseDb();
// if($tofile>0) $pdf->Output($filename, "F");
// else $pdf->Output($filename, "I");
$pdf->Output($filename, "F");
if($tofile==0) {
	header("Pragma: public"); // required
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("Cache-Control: private",false); // required for certain browsers
	header("Content-Type: application/force-download");
	header("Content-Disposition: attachment; filename=\"".basename($filename)."\";" );
	header("Content-Transfer-Encoding: binary");
	header("Content-Length: ".filesize($filename));
	readfile("$filename");
	if(file_exists($imagefn)) unlink($imagefn);
    if(file_exists($filename)) unlink("$filename");
	exit();
}
if(file_exists($imagefn)) unlink($imagefn);
?>
