<?php
//	Written by: Richard Gonsuron
//	Copyright: 2009, Supreme Source Energy Services, Inc.
//	All rights reserved.
//	NOTICE: This file is solely owned by Supreme Source Energy Services, Inc. You may NOT modify, copy,
//	or distribute this file in any manner without written permission of Supreme Source Energy Services, Inc.

//error_reporting(E_ALL);
//ini_set('display_errors', '1');

require('/usr/share/php/fpdf/fpdf.php');
require_once("dbio.class.php");

if(!isset($seldbname) or strlen($seldbname)<=0)	$seldbname=$_GET['seldbname'];
if(!isset($filename) or strlen($filename)<=0) $filename=(isset($_GET['filename']) ? $_GET['filename'] : '');

$db=new dbio($seldbname);
$db->OpenDb();
include('readwellinfo.inc.php');
include('readappinfo.inc.php');
$db->CloseDb();

$tofile=0;
if(strlen($filename)>0) $tofile=1;
else $filename=sprintf("tmp/%s.surveycl.pdf", $seldbname);
if(file_exists($filename)) unlink($filename);

$imgfn1="tmp/$seldbname.surveyplotcl.png";
if(file_exists($imgfn1)) unlink($imgfn1);

$args=" -t hor";
if(isset($cutoff) and strlen($cutoff))	$args=$args." -c $cutoff";
$args=$args." -o $imgfn1";
$args=$args." -h 698";
$args=$args." -w 1148";
$retstr = array(); $retval = 0;
exec("./sses_ps -d $seldbname $args",$retstr,$retval);
//echo "<p>cmd = ./sses_ps -d $seldbname $args</p>";
//echo "<p>retval = $retval</p>";
//echo '</p>'; print_r($retstr); echo '</p>';
//exit();

class PDF extends FPDF
{
	var $db;
	var $hdrheight=0.0;
	var $scaleright=200.0;

	function ReportHeader()
	{
		$this->SetMargins(.25,0,0);
		$this->Image("./logofull.png", .5, .2, .7, .55);
		$this->hdrheight+=0.75;

		$this->SetFont('','B',18);
		$this->Cell(8, .17, "Horizontal Survey Plot", 0, 0, 'C', false);
		$this->SetFontSize('5');
		$this->Cell(2.0, .1, "Generated by: Subsurface Geological Tracking Analysis", 0, 1, 'R', false);
		$this->Cell(10.2, .1, "Copyright 2010-2011 Supreme Source Energy Services, Inc.", 0, 1, 'R', false);
		$this->SetFontSize(7);
		$this->Ln();

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
			if( !strlen($wellname) ) $wellname="Polaris";
			$companyname=$this->db->FetchField("operatorname");
			$jobnumber=$this->db->FetchField("jobnumber");
			$operatorcontact=$this->db->FetchField("operatorcontact1");
			$rigid=$this->db->FetchField("rigid");
			$startdate=$this->db->FetchField("startdate");
			$apiuwi=$this->db->FetchField("wellid");
			$enddate=$this->db->FetchField("enddate");
			$field=$this->db->FetchField("field");
			$location=$this->db->FetchField("location");
			$propazm=$this->db->FetchField("propazm");
			$stateprov=$this->db->FetchField("stateprov");
			$northref=$this->db->FetchField("correction");
			$county=$this->db->FetchField("county");
		}
		$h=.13;
		$w1=1.0;
		$w2=1.75;
		$w3=0.38;
		$b=0;
		$this->SetFont('','',7);

		$this->Cell($w1, $h, "Company Name:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $companyname, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Field:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $field, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Job Number:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $jobnumber, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "Well Name:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $wellname, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Location:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $location, $b, 0, 'L', false);
		$this->Cell($w1, $h, "", $b, 0, 'R', false);
		$this->Cell($w2, $h, "", $b, 0, 'L', false);
		$this->Cell($w1, $h, "Proposed Azimuth:", $b, 0, 'R', false);
		$this->Cell($w3, $h, $propazm, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "Rig ID:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $rigid, $b, 0, 'L', false);
		$this->Cell($w1, $h, "State/Prov:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $stateprov, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Start Date:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $startdate, $b, 0, 'L', false);
		$this->Cell($w1, $h, "North Reference:", $b, 0, 'R', false);
		$this->Cell($w3, $h, $northref, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "API/UWI:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $apiuwi, $b, 0, 'L', false);
		$this->Cell($w1, $h, "County:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $county, $b, 0, 'L', false);
		$this->Cell($w1, $h, "End Date:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $enddate, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;
		$this->Ln(); $this->hdrheight+=$h;
		$this->hdrheight+=.5;
	}

	function ReportSurveys() {
		$db2=$this->db2;
		$db2->DoQuery("select * from addforms;");
		$totid =null;
		$botid = null;
		while($db2->FetchRow()){
			
			if(trim($db2->FetchField('label'))=='TOT'){
				$totid = $db2->FetchField('id');
			}
			if(trim($db2->FetchField('label'))=='BOT'){
				$botid = $db2->FetchField('id');
			}
		}
		$this->db->DoQuery("SELECT count(id) FROM surveys WHERE plan=0");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$numsvys=$this->db->FetchField("count");
		}

		$this->db->DoQuery("SELECT * FROM surveys WHERE plan=0 ORDER BY md DESC LIMIT 1");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$id= $this->db->FetchField("id");
			if($totid){
				$query = "select tot from addformsdata where svyid=$id and infoid=$totid;";
			 	$db2->DoQuery($query);
				$db2->FetchRow();
				$tot =sprintf("%.2f", $db2->FetchField("tot"));
			}
			if($botid){
				$query = "select tot from addformsdata where svyid=$id and infoid=$botid;";
				$db2->DoQuery($query);
				$db2->FetchRow();
				$bot =sprintf("%.2f", $db2->FetchField("tot"));
			}				
			$svymd=$this->db->FetchField("md");
			$svyinc=$this->db->FetchField("inc");
			$svyazm=$this->db->FetchField("azm");
			$svytvd=$this->db->FetchField("tvd");
			$svyvs=$this->db->FetchField("vs");
			$svydl=$this->db->FetchField("dl");
			$svyca=$this->db->FetchField("ca");
			$svycd=$this->db->FetchField("cd");
			$svyns=$this->db->FetchField("ns");
			$svyew=$this->db->FetchField("ew");
			$tlc = $this->db->FetchField("tot");
			$svytot=$tot;
			$svybot=$bot;
			$svydip=$this->db->FetchField("dip");
			$svyfault=$this->db->FetchField("fault");
		}

		$h=.125;
		$w1=0.50;
		$w2=0.36;
		$b=1;
		$left=3.75;
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(110, 174, 126);
		$this->Cell($left);
		$this->Cell($w2, $h, "Svy", $b, 0, 'C', true);
		$this->Cell($w1, $h, "Depth", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Inc", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Azm", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TVD", $b, 0, 'C', true);
		$this->Cell($w1, $h, "VS", $b, 0, 'C', true);
		$this->Cell($w2, $h, "DL", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TCL", $b, 0, 'C', true);
		$this->Cell($w2, $h, "Pos-TCL", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TOT", $b, 0, 'C', true);
		$this->Cell($w1, $h, "BOT", $b, 0, 'C', true);
		$this->Cell($w2, $h, "DIP", $b, 0, 'C', true);
		$this->Cell($w2, $h, "FAULT", $b, 0, 'C', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(230, 230, 190);
		$this->Cell($left);
		$this->Cell($w2, $h, sprintf("%d",$numsvys-1), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
		$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(250, 148, 148);
		$this->db->DoQuery("SELECT * FROM surveys WHERE plan>0 ORDER BY md ASC");

		if($this->db->FetchNumRows()>0) {
			$i=0;
			while ($this->db->FetchRow()) {
				$omd= $this->db->FetchField("md");
				if($totid){
					$query = "select tot from addformsdata where md=$omd and infoid=$totid;";
				 	$db2->DoQuery($query);
					$db2->FetchRow();
					$tot =sprintf("%.2f", $db2->FetchField("tot"));
				}
				if($botid){
					$query = "select tot from addformsdata where md=$omd and infoid=$botid;";
					$db2->DoQuery($query);
					$db2->FetchRow();
					$bot =sprintf("%.2f", $db2->FetchField("tot"));
				}				
				$svymd=$this->db->FetchField("md");
				$svyinc=$this->db->FetchField("inc");
				$svyazm=$this->db->FetchField("azm");
				$svytvd=$this->db->FetchField("tvd");
				$svyvs=$this->db->FetchField("vs");
				$svydl=$this->db->FetchField("dl");
				$svyca=$this->db->FetchField("ca");
				$svycd=$this->db->FetchField("cd");
				$svyns=$this->db->FetchField("ns");
				$svyew=$this->db->FetchField("ew");
				$tlc = $this->db->FetchField("tot");
				$svytot=$tot;
				$svybot=$bot;
				$svydip=$this->db->FetchField("dip");
				$svyfault=$this->db->FetchField("fault");

				$this->Cell($left);
				if($i==0) $this->Cell($w2, $h, "BPrj", $b, 0, 'R', true);
				else $this->Cell($w2, $h, "PAhd", $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
				$this->Ln(); $this->hdrheight+=$h;
				$i++;
			}
		}
	}

	function ReportProjections() {
		$db2=$this->db2;
		$h=.125;
		$w1=0.50;
		$w2=0.36;
		$b=1;
		$left=3.75;
		$this->SetFillColor(250, 148, 148);
		$db2->DoQuery("select * from addforms;");
		$totid =null;
		$botid = null;
		while($db2->FetchRow()){
			
			if(trim($db2->FetchField('label'))=='TOT'){
				$totid = $db2->FetchField('id');
			}
			if(trim($db2->FetchField('label'))=='BOT'){
				$botid = $db2->FetchField('id');
			}
		}
		$this->db->DoQuery("SELECT * FROM projections ORDER BY md ASC");
		if($this->db->FetchNumRows()>0) {
			$i=1;
			while ($this->db->FetchRow()) {
				$id = $this->db->FetchField("id");
				if($totid){
							$query = "select tot from addformsdata where projid=$id and infoid=$totid;";
							$db2->DoQuery($query);
							$db2->FetchRow();
							$tot =sprintf("%.2f", $db2->FetchField("tot"));
						}
				if($botid){
					$query = "select tot from addformsdata where projid=$id and infoid=$botid;";
					$db2->DoQuery($query);
					$db2->FetchRow();
					$bot =sprintf("%.2f", $db2->FetchField("tot"));
				}
				$svymd=$this->db->FetchField("md");
				$svyinc=$this->db->FetchField("inc");
				$svyazm=$this->db->FetchField("azm");
				$svytvd=$this->db->FetchField("tvd");
				$svyvs=$this->db->FetchField("vs");
				$svydl=$this->db->FetchField("dl");
				$svyca=$this->db->FetchField("ca");
				$svycd=$this->db->FetchField("cd");
				$svyns=$this->db->FetchField("ns");
				$svyew=$this->db->FetchField("ew");
				$tlc = $this->db->FetchField("tot");
				$svytot=$tot;
				$svybot=$bot;
				$svydip=$this->db->FetchField("dip");
				$svyfault=$this->db->FetchField("fault");

				$this->Cell($left);
				$this->Cell($w2, $h, "PA$i", $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydl), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$tlc), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$tlc-$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svydip), $b, 0, 'R', true);
				$this->Cell($w2, $h, sprintf("%0.2f",$svyfault), $b, 0, 'R', true);
				$this->Ln(); $this->hdrheight+=$h;
				$i++;
			}
		}
		$this->Ln(); $this->hdrheight+=$h;
	}

	function PlotImage()
	{
		global $imgfn1, $propazm;
		$y=$this->hdrheight+.5;
		$h=7.5-$this->hdrheight-.5;
		$this->Image($imgfn1, 0.5, $y, 10.0, $h);

		// $ra=90.0-$propazm;
		// exec("convert -rotate $ra compass.jpg tmp/compass.jpg");
		// $this->Image("tmp/compass.jpg", 8.0, $y+.2, 1.0, 1.0);
	}
}

$pdf=new PDF("L", "in", "Letter");
$pdf->scaleright=$scaleright;
$pdf->SetFont('Arial','',8);
$pdf->AddPage();
$pdf->db=new dbio($seldbname);
$pdf->db->OpenDb();
$pdf->db2=new dbio($seldbname);
$pdf->db2->OpenDb();
$pdf->ReportHeader();
$pdf->PlotImage();
$pdf->ReportSurveys();
$pdf->ReportProjections();
$pdf->db->CloseDb();
$pdf->db2->CloseDb();

// if($tofile>0) $pdf->Output($filename, "F");
// else $pdf->Output($filename, "I");
$pdf->Output($filename, "F");

//echo "<p>filename=$filename tofile=$tofile</p>";

if($tofile==0) {
	header("Pragma: public"); // required
	header("Expires: 0");
	header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
	header("Cache-Control: private",false); // required for certain browsers
	header("Content-Type: application/force-download");
	header("Content-Disposition: attachment; filename=\"".basename($filename)."\";" );
	header("Content-Transfer-Encoding: binary");
	header("Content-Length: ".filesize($filename));
	readfile("$filename");
    if(file_exists($filename)) unlink("$filename");
}
if(file_exists($imgfn1)) unlink($imgfn1);
?>
