<?php /*
	Written by: Richard Gonsuron
	Copyright: 2009, Supreme Source Energy Services, Inc.
	All rights reserved.
	NOTICE: This file is solely owned by Supreme Source Energy Services, Inc. You may NOT modify, copy,
	or distribute this file in any manner without written permission of Supreme Source Energy Services, Inc.
*/ ?>
<?php
require('/usr/share/php/fpdf/fpdf.php');
require_once("dbio.class.php");
$ret=$_POST['ret'];
$seldbname=$_POST['seldbname'];
if($seldbname=="")	$seldbname=$_GET['seldbname'];
if(strlen($filename)<=0)	$filename=$_GET['filename'];
if(strlen($plotstart)<=0)	$plotstart=$_GET['plotstart'];
if(strlen($plotend)<=0)	$plotend=$_GET['plotend'];
if(strlen($wlid)<=0)	$wlid=$_GET['wlid'];

$db=new dbio($seldbname);
$db->OpenDb();
include "generatepdfimageleft.php";
include('readwellinfo.inc.php');
include('readappinfo.inc.php');
$db->DoQuery("SELECT * FROM surveys WHERE plan=0 ORDER BY md DESC LIMIT 1");
if($db->FetchNumRows()>0) {
	$db->FetchRow();
	$svymd=$db->FetchField("md");
	$svyinc=$db->FetchField("inc");
	$svyazm=$db->FetchField("azm");
	$svytvd=$db->FetchField("tvd");
	$svyvs=$db->FetchField("vs");
	$svyvs=$db->FetchField("vs");
	$svyca=$db->FetchField("ca");
	$svycd=$db->FetchField("cd");
	$svyns=$db->FetchField("ns");
	$svyew=$db->FetchField("ew");
	$svytot=$db->FetchField("tot");
	$svybot=$svytot-$svytvd;
}
$db->CloseDb();

$tofile=0;
if(strlen($filename)>0) $tofile=1;
else $filename="/tmp/$seldbname.snapshot.pdf";
if(file_exists($filename)) unlink($filename);
$imgfn="/tmp/$seldbname.snapshot.png";
if(file_exists($imgfn)) unlink($imgfn);

class PDF extends FPDF
{
	var $db;
	var $hdrheight=0.0;

	function ReportHeaderLandscape()
	{
		$this->SetMargins(1.0,0,0);
		$this->Image("./logofull.png", .5, .2, .7, .55);
		$this->hdrheight+=0.75;

		$this->SetFont('','B',18);
		$this->Cell(8.0, .17, "Snapshot View", 0, 0, 'C', false);
		$this->SetFontSize('5');
		$this->Cell(2.0, .1, "Generated by: Subsurface Geological Tracking Analysis", 0, 2, 'R', false);
		$this->Cell(2.0, .1, "Copyright 2010-2011 Supreme Source Energy Services, Inc.", 0, 1, 'R', false);

		$this->SetFontSize('7');
		$this->Ln();

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
			if( !strlen($wellname) ) $wellname="Polaris";
			$companyname=$this->db->FetchField("operatorname");
			$jobnumber=$this->db->FetchField("jobnumber");
			$operatorcontact=$this->db->FetchField("operatorcontact");
			$rigid=$this->db->FetchField("rigid");
			$startdate=$this->db->FetchField("startdate");
			$apiuwi=$this->db->FetchField("wellid");
			$enddate=$this->db->FetchField("enddate");
			$field=$this->db->FetchField("field");
			$location=$this->db->FetchField("location");
			$propazm=$this->db->FetchField("propazm");
			$stateprov=$this->db->FetchField("stateprov");
			$northref=$this->db->FetchField("correction");
			$county=$this->db->FetchField("county");
			$country=$this->db->FetchField("country");
		}
		$h=.13;
		$w1=1.0;
		$w2=1.75;
		$w3=0.38;
		$b=0;
		$this->SetFont('','',7);

		$this->Cell($w1, $h, "Company Name:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $companyname, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Field:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $field, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Job Number:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $jobnumber, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "Well Name:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $wellname, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Location:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $location, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Proposed Azimuth:", $b, 0, 'R', false);
		$this->Cell($w3, $h, $propazm, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "Rig ID:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $rigid, $b, 0, 'L', false);
		$this->Cell($w1, $h, "State/Prov:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $stateprov, $b, 0, 'L', false);
		$this->Cell($w1, $h, "Start Date:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $startdate, $b, 0, 'L', false);
		$this->Cell($w1, $h, "North Reference:", $b, 0, 'R', false);
		$this->Cell($w3, $h, $northref, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;

		$this->Cell($w1, $h, "API/UWI:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $apiuwi, $b, 0, 'L', false);
		$this->Cell($w1, $h, "County:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $county, $b, 0, 'L', false);
		$this->Cell($w1, $h, "End Date:", $b, 0, 'R', false);
		$this->Cell($w2, $h, $enddate, $b, 0, 'L', false);
		$this->Ln(); $this->hdrheight+=$h;
		$this->Ln(); $this->hdrheight+=$h;
	}

	function ReportHeaderPortrait()
	{
		$h=.15;
		$w1=1.0;
		$w2=1.75;
		$w3=0.64;

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows() > 0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
		}
		// $this->SetFillColor(255,255,255);
		// $this->SetFillColor(230, 230, 190);

		$this->SetMargins(1.5,0,.25);
		$this->SetFont('','B',14);
		$this->SetY(0.25);
		// $this->SetX(3.175);
		$this->Cell(.7, .55, "", 0, 0, 'C', false);
		$this->Cell(3.8, .5, "Snapshot View", 0, 0, 'C', false);
		$this->SetFontSize('5');
		$this->Cell(2.0, .1, "Generated by: Subsurface Geological Tracking Analysis", 0, 2, 'R', false);
		$this->Cell(2.0, .1, "Copyright 2010-2011 Supreme Source Energy Services, Inc.", 0, 1, 'R', false);

		$this->SetFont('','',7);
		$this->Ln();
		$this->Ln();
		$this->Ln();

		$this->Image("./logofull.png", 1.52, .25, .6, .5);

		$this->db->DoQuery("SELECT * FROM surveys WHERE plan=0 ORDER BY md DESC LIMIT 1");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$svymd=$this->db->FetchField("md");
			$svyinc=$this->db->FetchField("inc");
			$svyazm=$this->db->FetchField("azm");
			$svytvd=$this->db->FetchField("tvd");
			$svyvs=$this->db->FetchField("vs");
			$svyvs=$this->db->FetchField("vs");
			$svyca=$this->db->FetchField("ca");
			$svycd=$this->db->FetchField("cd");
			$svyns=$this->db->FetchField("ns");
			$svyew=$this->db->FetchField("ew");
			$svytot=$this->db->FetchField("tot");
			$svybot=$svytot-$svytvd;
		}

		$this->db->DoQuery("SELECT * FROM wellinfo;");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$wellname=$this->db->FetchField("wellborename");
			if( !strlen($wellname) ) $wellname="Polaris";
			$companyname=$this->db->FetchField("operatorname");
			$jobnumber=$this->db->FetchField("jobnumber");
			$operatorcontact=$this->db->FetchField("operatorcontact");
			$rigid=$this->db->FetchField("rigid");
			$startdate=$this->db->FetchField("startdate");
			$apiuwi=$this->db->FetchField("wellid");
			$enddate=$this->db->FetchField("enddate");
			$field=$this->db->FetchField("field");
			$location=$this->db->FetchField("location");
			$propazm=$this->db->FetchField("propazm");
			$stateprov=$this->db->FetchField("stateprov");
			$northref=$this->db->FetchField("correction");
			$county=$this->db->FetchField("county");
			$country=$this->db->FetchField("country");
		}

		$this->Cell($w1, $h, "Company Name:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $companyname, 0, 0, 'L', false);
		$this->Cell($w1, $h, "Job Number:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $jobnumber, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "Well Name:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $wellname, 0, 0, 'L', false);
		$this->Cell($w1, $h, "Rig ID:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $rigid, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "API/UWI:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $apiuwi, 0, 0, 'L', false);
		$this->Cell($w1, $h, "Start Date:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $startdate, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "Field:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $field, 0, 0, 'L', false);
		$this->Cell($w1, $h, "End Date:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $enddate, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "Location:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $location, 0, 0, 'L', false);
		$this->Cell($w1, $h, "Proposed Azimuth:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $propazm, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "State/Prov:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $stateprov, 0, 0, 'L', false);
		$this->Cell($w1, $h, "North Reference:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $northref, 0, 0, 'L', false);
		$this->Ln();

		$this->Cell($w1, $h, "County:", 0, 0, 'R', false);
		$this->Cell($w2, $h, $county, 0, 0, 'L', false);
		$this->Cell($w1, $h, "", 0, 0, 'C', false);
		$this->Cell($w2, $h, "", 0, 0, 'C', false);
		$this->Ln();

		// $this->Ln();
	}

	function ReportSurveys() {
		$this->db->DoQuery("SELECT * FROM surveys WHERE plan=0 ORDER BY md DESC LIMIT 1");
		if($this->db->FetchNumRows()>0) {
			$this->db->FetchRow();
			$svymd=$this->db->FetchField("md");
			$svyinc=$this->db->FetchField("inc");
			$svyazm=$this->db->FetchField("azm");
			$svytvd=$this->db->FetchField("tvd");
			$svyvs=$this->db->FetchField("vs");
			$svyvs=$this->db->FetchField("vs");
			$svyca=$this->db->FetchField("ca");
			$svycd=$this->db->FetchField("cd");
			$svyns=$this->db->FetchField("ns");
			$svyew=$this->db->FetchField("ew");
			$svytot=$this->db->FetchField("tot");
			$svybot=$svytot-$svytvd;
		}

		$h=.125;
		$w1=0.64;
		$b=1;
		// $left=.5;
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(110, 174, 126);
		// $this->Cell($left);
		$this->Cell($w1, $h, "Depth", $b, 0, 'C', true);
		$this->Cell($w1, $h, "Inc", $b, 0, 'C', true);
		$this->Cell($w1, $h, "Azm", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TVD", $b, 0, 'C', true);
		$this->Cell($w1, $h, "N/-S", $b, 0, 'C', true);
		$this->Cell($w1, $h, "E/-W", $b, 0, 'C', true);
		$this->Cell($w1, $h, "VS", $b, 0, 'C', true);
		$this->Cell($w1, $h, "TCL", $b, 0, 'C', true);
		$this->Cell($w1, $h, "Pos-TCL", $b, 0, 'C', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(230, 230, 190);
		// $this->Cell($left);
		$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyns), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyew), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
		$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
		$this->Ln(); $this->hdrheight+=$h;

		$this->SetFillColor(250, 148, 148);
		$this->db->DoQuery("SELECT * FROM surveys WHERE plan>0 ORDER BY md ASC");
		if($this->db->FetchNumRows()>0) {
			while ($this->db->FetchRow()) {
				$svymd=$this->db->FetchField("md");
				$svyinc=$this->db->FetchField("inc");
				$svyazm=$this->db->FetchField("azm");
				$svytvd=$this->db->FetchField("tvd");
				$svyvs=$this->db->FetchField("vs");
				$svyvs=$this->db->FetchField("vs");
				$svyca=$this->db->FetchField("ca");
				$svycd=$this->db->FetchField("cd");
				$svyns=$this->db->FetchField("ns");
				$svyew=$this->db->FetchField("ew");
				$svytot=$this->db->FetchField("tot");
				$svybot=$svytot-$svytvd;

				// $this->Cell($left);
				$this->Cell($w1, $h, sprintf("%0.2f",$svymd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyinc), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyazm), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytvd), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyns), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyew), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svyvs), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svytot), $b, 0, 'R', true);
				$this->Cell($w1, $h, sprintf("%0.2f",$svybot), $b, 0, 'R', true);
				$this->Ln(); $this->hdrheight+=$h;
			}
		}
		$this->Ln(); $this->hdrheight+=$h;
	}

	function PlotImage()
	{
		global $imgfn, $viewrotds, $scaleright,$seldbname;
		$imgfn2="./tmp/$seldbname"."_gva_tab4snap.png";
		if($viewrotds>0) {
			$this->Image("$imgfn2", .75, 3.5, 9.75, 4.0);
			$this->Text(.5, 3.8, "$scaleright");
			$this->Text(.5, 7.2, "0");
		} else {
			
			$this->Image("$imgfn2", 1.35, 2.65, 4, 7.65);
			$this->Text(1.5, 10.4, "0");
			$this->Text(5.0, 10.4, "$scaleright");
		}
	}
}

// set pixel density
$pheight=11*200;
$pwidth=4*200;

if("$wlid"!="")
	exec ("./sses_gpd -wlid $wlid -r $scaleright -d $seldbname -o $imgfn -cld -wld -w $pwidth -h $pheight -s $plotstart -e $plotend -lw 2 -fs 20 -ps 1");
else
	exec ("./sses_gpd -r $scaleright -d $seldbname -o $imgfn -cld -wld -w $pwidth -h $pheight -s $plotstart -e $plotend -lw 2 -fs 20 -ps 1");

if($viewrotds>0) $pdf=new PDF('L', "in", "letter");
else $pdf=new PDF('P', "in", "letter");
$pdf->SetFont('Arial','',8);
$pdf->AddPage();
$pdf->db=new dbio($seldbname);
$pdf->db->OpenDb();
if($viewrotds>0)
	$pdf->ReportHeaderLandscape();
else
	$pdf->ReportHeaderPortrait();
$pdf->ReportSurveys();
$pdf->PlotImage();
$pdf->db->CloseDb();

// $pdf->SetMargins(.25, .25, .25);
// $pdf->Cell(4, .125, "Image starts here", 1, 1, 'C', false);
// $pdf->SetFont('Arial','',9);
// $pdf->Output("./tmp/welllog.pdf", "I");
if($tofile>0) $pdf->Output($filename, "F");
else $pdf->Output($filename, "I");
?>

